spring.data.mongodb:
  database: teambuilting # Database name.
  host: localhost # Mongo server host.
  # password: # Login password of the mongo server.
  port: 27017 # Mongo server port.
  repositories.enabled: true # Enable Mongo repositories.
  username: # Login user of the mongo server.

endpoints:
  enabled: true # Enable endpoints.
  actuator.enabled: true # Enable the endpoint.